# Karpenter NodePool Configuration Example
# This shows how to configure Karpenter to add the unverified taint to new nodes

apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      # Add the unverified taint to new nodes
      # This prevents workloads from scheduling until verification completes
      taints:
        - key: node-ready/unverified
          value: "true"
          effect: NoSchedule

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3.large", "t3.xlarge"]

      # Node class reference
      nodeClassRef:
        name: default

  # Limits for the node pool
  limits:
    cpu: 1000
    memory: 1000Gi

  # Disruption budget
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 days

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "KarpenterNodeRole-${CLUSTER_NAME}"

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"

  userData: |
    #!/bin/bash
    # Custom user data if needed
    echo "Node starting up..."

  tags:
    Name: "${CLUSTER_NAME}-karpenter-node"
    Environment: production
    ManagedBy: karpenter
