# Example Karpenter NodeClaim resource that would be managed by this tool
# This is an example of what a NodeClaim looks like - kube-node-ready will
# automatically detect and prefer to delete NodeClaims over direct node deletion
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  name: example-nodeclaim
  labels:
    karpenter.sh/nodepool: "default"
    karpenter.sh/provisioner-name: "default"
spec:
  nodeClassRef:
    apiVersion: karpenter.k8s.aws/v1beta1
    kind: EC2NodeClass
    name: default
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.xlarge"]
status:
  nodeName: "ip-192-168-1-100.us-west-2.compute.internal"  # This is what kube-node-ready uses to match
  conditions:
    - type: Ready
      status: "True"
      lastTransitionTime: "2024-01-01T00:00:00Z"

